services:
  backend:
    build:
      context: ./API-pokedex-pokemon-card
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "server=${MYSQL_SERVER};port=3306;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./front-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always
