services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pokedex-pokemon-db
    ports:
      - "3307:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./API-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./front-pokedex-pokemon-card
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-pokedex-pokemon-card/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
