version: "3.8"

services:
  backend:
    build:
      context: ./API-pokedex-pokemon-card
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD}"
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build:
      context: ./front-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
