services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pokedex-pokemon-db
    ports:
      - "3307:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./API-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - Jwt__Key=une-cle-secrete-très-longue-pour-le-token-jwt
      - Jwt__Issuer=https://localhost:5001
      - Jwt__Audience=https://localhost:5001
      # - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./front-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge
