version: '3.9'

services:
  backend:
    build:
      context: ./API-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./front-pokedex-pokemon-card
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
